_wandb:
    value:
        cli_version: 0.22.0
        e:
            2r4o5edhx578gp06gs6ztxj6ki67adh1:
                args:
                    - --config
                    - /home/kylee/LongVALE/configs/eval.json
                codePath: longvalellm/eval/eval.py
                codePathLocal: longvalellm/eval/eval.py
                email: lky3685@gmail.com
                executable: /home/kylee/anaconda3/envs/longvale/bin/python
                git:
                    commit: 2eb88ce3f72458faea6f3db8f841b41e6485a814
                    remote: git@github.com:Yooonlee/LongVALE.git
                host: kylee-gpu5090
                os: Linux-6.14.0-27-generic-x86_64-with-glibc2.39
                program: /home/kylee/LongVALE/longvalellm/eval/eval.py
                python: CPython 3.10.18
                root: /home/kylee/LongVALE
                startedAt: "2025-09-20T07:25:12.159844Z"
                writerId: 2r4o5edhx578gp06gs6ztxj6ki67adh1
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 98
            "2":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 98
            "3":
                - 16
            "4": 3.10.18
            "5": 0.22.0
            "6": 4.56.2
            "12": 0.22.0
            "13": linux-x86_64
asr_feat_folder:
    value: /home/kylee/LongVALE/data/eval/speech_features_1171
audio_feat_folder:
    value: /home/kylee/LongVALE/data/eval/audio_features_1171
config:
    value: /home/kylee/LongVALE/configs/eval.json
data_path:
    value: /home/kylee/LongVALE/data/eval/longvale-annotations-eval.json
log_path:
    value: /home/kylee/LongVALE/logs/eval
model_base:
    value: checkpoints/vicuna-7b-v1.5
pretrain_asr_mlp_adapter:
    value: null
pretrain_audio_mlp_adapter:
    value: null
pretrain_mm_mlp_adapter:
    value: checkpoints/vtimellm_stage1_mm_projector.bin
stage2:
    value: checkpoints/longvalellm-vicuna-v1-5-7b/longvale-vicuna-v1-5-7b-stage2-bp
stage3:
    value: checkpoints/longvalellm-vicuna-v1-5-7b/longvale-vicuna-v1-5-7b-stage3-it
task:
    value: all
video_feat_folder:
    value: /home/kylee/LongVALE/data/eval/video_features_1171
