_wandb:
    value:
        cli_version: 0.22.0
        e:
            an34pmc7b3hlav1wf2jxvafx2duu6bla:
                args:
                    - --config
                    - /home/kylee/LongVALE/configs/eval.json
                codePath: longvalellm/eval/eval.py
                codePathLocal: longvalellm/eval/eval.py
                cpu_count: 16
                cpu_count_logical: 32
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "97829425152"
                        used: "28163411968"
                email: lky3685@gmail.com
                executable: /home/kylee/anaconda3/envs/longvale/bin/python
                git:
                    commit: c9fa81e7d5475b634944fb5ded149669431bd0bd
                    remote: git@github.com:Yooonlee/LongVALE.git
                gpu: NVIDIA GeForce RTX 5090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 21760
                      memoryTotal: "34190917632"
                      name: NVIDIA GeForce RTX 5090
                      uuid: GPU-8c696531-3ec2-bd8a-86ac-6438db1ac4c8
                host: kylee-gpu5090
                memory:
                    total: "64940851200"
                os: Linux-6.14.0-29-generic-x86_64-with-glibc2.39
                program: /home/kylee/LongVALE/longvalellm/eval/eval.py
                python: CPython 3.10.18
                root: /home/kylee/LongVALE
                startedAt: "2025-09-23T05:33:36.433366Z"
                writerId: an34pmc7b3hlav1wf2jxvafx2duu6bla
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 98
            "2":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 98
            "3":
                - 16
            "4": 3.10.18
            "5": 0.22.0
            "6": 4.31.0
            "12": 0.22.0
            "13": linux-x86_64
asr_feat_folder:
    value: /home/kylee/LongVALE/data/eval/speech_features_1171
audio_feat_folder:
    value: /home/kylee/LongVALE/data/eval/audio_features_1171
config:
    value: /home/kylee/LongVALE/configs/eval.json
data_path:
    value: /home/kylee/LongVALE/data/eval/longvale-annotations-eval.json
log_path:
    value: /home/kylee/LongVALE/logs/eval.txt
model_base:
    value: checkpoints/vicuna-7b-v1.5
pretrain_asr_mlp_adapter:
    value: null
pretrain_audio_mlp_adapter:
    value: null
pretrain_mm_mlp_adapter:
    value: checkpoints/vtimellm_stage1_mm_projector.bin
stage2:
    value: checkpoints/longvalellm-vicuna-v1-5-7b/longvale-vicuna-v1-5-7b-stage2-bp
stage3:
    value: checkpoints/longvalellm-vicuna-v1-5-7b/longvale-vicuna-v1-5-7b-stage3-it
task:
    value: all
video_feat_folder:
    value: /home/kylee/LongVALE/data/eval/video_features_1171
