_wandb:
    value:
        cli_version: 0.23.0
        e:
            es16pbjj4mtu8sfpy4p3jv9nkv3meqz8:
                args:
                    - --data_path
                    - /home/kylee/workspace/LongVALE/data/longvale-annotations-eval.json
                    - --video_feat_folder
                    - /home/kylee/workspace/LongVALE/data/features_eval/video_features_1171
                    - --audio_feat_folder
                    - /home/kylee/workspace/LongVALE/data/features_eval/audio_features_1171
                    - --asr_feat_folder
                    - /home/kylee/workspace/LongVALE/data/features_eval/speech_features_1171
                    - --task
                    - all
                    - --log_path
                    - /home/kylee/workspace/LongVALE/eval_logs
                cpu_count: 128
                cpu_count_logical: 128
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "1882691960832"
                        used: "1088372236288"
                email: lky3685@gmail.com
                executable: /root/datasets/kylee/anaconda3/envs/longvale2/bin/python
                git:
                    commit: cc8fdf9ec8f09587828f414c688849c6b29bfb00
                    remote: https://github.com/Yooonlee/LongVALE.git
                gpu: NVIDIA RTX A6000
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-dc3b067e-3f46-e73c-b7a5-a64580376a9d
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-94fc1b8b-fed1-1878-c36a-a128128899c1
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-ae784f3d-8801-8376-fce7-e2a843551899
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-281054d9-7536-8e1c-fc20-cddc71528082
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-4376da49-33b1-e49d-97f6-58f4220f941a
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-2249ec8e-161d-6e4a-e84e-8850f59e2993
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-297642e2-f62c-aefa-0ce8-fb7e9fb4beca
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-c69c56f0-4bfc-2d90-6a04-a395f8d563d6
                host: d8cb9cd46bb8
                memory:
                    total: "1081968746496"
                os: Linux-5.4.0-196-generic-x86_64-with-glibc2.31
                program: /home/kylee/workspace/LongVALE/longvalellm/eval/eval.py
                python: CPython 3.10.19
                root: /root/workspace/kylee/LongVALE
                startedAt: "2025-11-20T23:37:54.660775Z"
                writerId: es16pbjj4mtu8sfpy4p3jv9nkv3meqz8
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 98
                - 105
            "2":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 98
                - 105
            "3":
                - 16
            "4": 3.10.19
            "5": 0.23.0
            "6": 4.31.0
            "12": 0.23.0
            "13": linux-x86_64
asr_feat_folder:
    value: /home/kylee/workspace/LongVALE/data/features_eval/speech_features_1171
audio_feat_folder:
    value: /home/kylee/workspace/LongVALE/data/features_eval/audio_features_1171
config:
    value: null
data_path:
    value: /home/kylee/workspace/LongVALE/data/longvale-annotations-eval.json
log_path:
    value: /home/kylee/workspace/LongVALE/eval_logs
model_base:
    value: checkpoints/vicuna-7b-v1.5
pretrain_asr_mlp_adapter:
    value: null
pretrain_audio_mlp_adapter:
    value: null
pretrain_mm_mlp_adapter:
    value: checkpoints/vtimellm_stage1_mm_projector.bin
stage2:
    value: checkpoints/longvalellm-vicuna-v1-5-7b/longvale-vicuna-v1-5-7b-stage2-bp
stage3:
    value: checkpoints/longvalellm-vicuna-v1-5-7b/longvale-vicuna-v1-5-7b-stage3-it
task:
    value: all
video_feat_folder:
    value: /home/kylee/workspace/LongVALE/data/features_eval/video_features_1171
