_wandb:
    value:
        cli_version: 0.23.0
        e:
            2e3m6dqvrjcqz3z7zq19dksf677tcxe5:
                args:
                    - --input
                    - /home/kylee/workspace/LongVALE/data_backup/before_postprocess/Tree-Step3_part1.json
                    - --output-dir
                    - /home/kylee/kylee/LongVALE/data/after_postprocess
                    - --speech-json-dir
                    - /home/kylee/kylee/LongVALE/data/speech_asr_1171
                    - --not-json-dir
                    - /home/kylee/kylee/LongVALE/logs/wrong_sample_1015.txt
                cpu_count: 128
                cpu_count_logical: 128
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "1882691960832"
                        used: "995717771264"
                email: lky3685@gmail.com
                executable: /root/datasets/kylee/anaconda3/envs/mistral/bin/python
                git:
                    commit: 1cab3bc483db276fd9344393df22faae8e31024f
                    remote: https://github.com/Yooonlee/LongVALE.git
                gpu: NVIDIA RTX A6000
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-dc3b067e-3f46-e73c-b7a5-a64580376a9d
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-94fc1b8b-fed1-1878-c36a-a128128899c1
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-ae784f3d-8801-8376-fce7-e2a843551899
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-281054d9-7536-8e1c-fc20-cddc71528082
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-4376da49-33b1-e49d-97f6-58f4220f941a
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-2249ec8e-161d-6e4a-e84e-8850f59e2993
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-297642e2-f62c-aefa-0ce8-fb7e9fb4beca
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-c69c56f0-4bfc-2d90-6a04-a395f8d563d6
                host: d8cb9cd46bb8
                memory:
                    total: "1081968746496"
                os: Linux-5.4.0-196-generic-x86_64-with-glibc2.31
                program: /home/kylee/workspace/LongVALE/postprocess/postprocess.py
                python: CPython 3.10.19
                root: /root/workspace/kylee/LongVALE/postprocess
                startedAt: "2025-11-17T12:15:58.981856Z"
                writerId: 2e3m6dqvrjcqz3z7zq19dksf677tcxe5
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 11
                - 49
                - 71
            "2":
                - 1
                - 11
                - 49
                - 71
            "3":
                - 13
                - 15
                - 16
            "4": 3.10.19
            "5": 0.23.0
            "6": 4.57.1
            "12": 0.23.0
            "13": linux-x86_64
description:
    value: Plain version without NER processing
features:
    value:
        - basic_processing
        - llm_calls
model:
    value: meta-llama/Meta-Llama-3-8B-Instruct
version:
    value: plain
